# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_auto_20160628_0332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='for_doctor',
        ),
        migrations.AddField(
            model_name='notification',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
