# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-15 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_auto_20160915_0112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='string',
            new_name='text',
        ),
    ]
