# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160622_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='using_doctor',
            field=models.NullBooleanField(),
        ),
    ]
