# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_client_my_doctors'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='doctor_requests',
            field=models.ManyToManyField(related_name='my_requests', to='accounts.Doctor'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='client_requests',
            field=models.ManyToManyField(related_name='my_requests', to='accounts.Client'),
        ),
        migrations.AlterField(
            model_name='client',
            name='my_doctors',
            field=models.ManyToManyField(related_name='my_clients', to='accounts.Doctor'),
        ),
    ]
