# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20160627_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='doctor_requests',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='client_requests',
        ),
    ]
