# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_myuser_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='description',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.CharField(blank=True, max_length=144, null=True),
        ),
    ]
