# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20160804_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='connections',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='images/profile/Screen_Shot_2016-07-13_at_9.42.02_AM.png', upload_to='images/profile'),
        ),
    ]
