# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20160804_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='connections',
            field=models.ManyToManyField(related_name='_userprofile_connections_+', to='accounts.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(null=True, upload_to='images/profile'),
        ),
    ]
