# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-14 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20160914_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='connections',
            field=models.ManyToManyField(blank=True, related_name='_userprofile_connections_+', to='accounts.UserProfile'),
        ),
    ]
