# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-15 00:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20160914_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='my_doctors',
        ),
        migrations.RemoveField(
            model_name='client',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='using_doctor',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
